checkPropertyDetail(X) :-
    (namaLokasi(X, Name),
    deskripsiLokasi(X, Description),
    format('Nama Lokasi                 : ~w~N', [Name]),
    format('Deskripsi Lokasi            : ~w~N', [Description]), nl,
    buy(X, 0, R),
    format('Harga Tanah                 : ~w~N', [R]),
    buy(X, 1, R1),
    format('Harga Bangunan ~w            : ~w~N', [1, R1]),
    buy(X, 2, R2),
    format('Harga Bangunan ~w            : ~w~N', [2, R2]),
    buy(X, 3, R3),
    format('Harga Bangunan ~w            : ~w~N', [3, R3]),
    buy(X, 4, R4),
    format('Harga Bangunan Landmark     : ~w~N', [R4]), nl,
    rent(X, 0, R5),
    format('Biaya Sewa Tanah            : ~w~N', [R5]),
    rent(X, 1, R6),
    format('Biaya Sewa Bangunan ~w       : ~w~N', [1, R6]),
    rent(X, 2, R7),
    format('Biaya Sewa Bangunan ~w       : ~w~N', [2, R7]),
    rent(X, 3, R8),
    format('Biaya Sewa Bangunan ~w       : ~w~N', [3, R8]),
    rent(X, 4, R9),
    format('Biaya Sewa Landmark         : ~w~N', [R9]), !) ; 
    format('~w bukan merupakan lokasi yang valid! Silahkan masukkan lokasi yang tepat.', [X]).