map :-
    milikBangunan(a1, Milik1),
    milikBangunan(a2, Milik2),
    milikBangunan(a3, Milik3),
    milikBangunan(b1, Milik4),
    milikBangunan(b2, Milik5),
    milikBangunan(b3, Milik6),
    milikBangunan(c1, Milik7),
    milikBangunan(c2, Milik8),
    milikBangunan(c3, Milik9),
    milikBangunan(d1, Milik10),
    milikBangunan(d2, Milik11),
    milikBangunan(d3, Milik12),
    milikBangunan(e1, Milik13),
    milikBangunan(e2, Milik14),
    milikBangunan(e3, Milik15),
    milikBangunan(f1, Milik16),
    milikBangunan(f2, Milik17),
    milikBangunan(f3, Milik18),
    milikBangunan(g1, Milik19),
    milikBangunan(g2, Milik20),
    milikBangunan(g3, Milik21),
    milikBangunan(h1, Milik22),
    milikBangunan(h2, Milik23),
    tingkatBangunan(a1, Tingkat1),
    tingkatBangunan(a2, Tingkat2),
    tingkatBangunan(a3, Tingkat3),
    tingkatBangunan(b1, Tingkat4),
    tingkatBangunan(b2, Tingkat5),
    tingkatBangunan(b3, Tingkat6),
    tingkatBangunan(c1, Tingkat7),
    tingkatBangunan(c2, Tingkat8),
    tingkatBangunan(c3, Tingkat9),
    tingkatBangunan(d1, Tingkat10),
    tingkatBangunan(d2, Tingkat11),
    tingkatBangunan(d3, Tingkat12),
    tingkatBangunan(e1, Tingkat13),
    tingkatBangunan(e2, Tingkat14),
    tingkatBangunan(e3, Tingkat15),
    tingkatBangunan(f1, Tingkat16),
    tingkatBangunan(f2, Tingkat17),
    tingkatBangunan(f3, Tingkat18),
    tingkatBangunan(g1, Tingkat19),
    tingkatBangunan(g2, Tingkat20),
    tingkatBangunan(g3, Tingkat21),
    tingkatBangunan(h1, Tingkat22),
    tingkatBangunan(h2, Tingkat23),
    write('\n'),
    format('           ~w~w   ~w~w   ~w~w        ~w~w   ~w~w   ~w~w          \n', [Milik13,Tingkat13,Milik14,Tingkat14,Milik15,Tingkat15,Milik16,Tingkat16,Milik17,Tingkat17,Milik18,Tingkat18]),
    format('    ----------------------------------------------   \n', []),
    format('    | FP | E1 | E2 | E3 | CC | F1 | F2 | F3 | WT |   \n', []),
    format(' ~w~w | D3 |----------------------------------| G1 | ~w~w\n', [Milik12,Tingkat12,Milik19,Tingkat19]),
    format(' ~w~w | D2 |                                  | G2 | ~w~w\n', [Milik11,Tingkat11,Milik20,Tingkat20]),
    format(' ~w~w | D1 |          L E T S  G E T          | G3 | ~w~w\n', [Milik10,Tingkat10,Milik21,Tingkat21]),
    format('    | TX |              R I C H             | TX | \n', []),
    format(' ~w~w | C3 |                                  | CC | \n', [Milik9,Tingkat9]),
    format(' ~w~w | C2 |                                  | H1 | ~w~w\n', [Milik8,Tingkat8,Milik22,Tingkat22]),
    format(' ~w~w | C1 |----------------------------------| H2 | ~w~w\n', [Milik7,Tingkat7,Milik23,Tingkat23]),
    format('    | JL | B3 | B2 | B1 | CF | A3 | A2 | A1 | GO |   \n', []),
    format('    ----------------------------------------------   \n', []),
    format('           ~w~w   ~w~w   ~w~w        ~w~w   ~w~w   ~w~w          \n', [Milik6,Tingkat6,Milik5,Tingkat5,Milik4,Tingkat4,Milik3,Tingkat3,Milik2,Tingkat2,Milik1,Tingkat1]),
    write('\n'),
    write('Posisi pemain:\n'),
    lokasiP(LokasiI, v),
    lokasiP(LokasiII, w),
    format('v = ~w\n', [LokasiI]),
    format('w = ~w\n', [LokasiII]), !.